name: CI-CD-GCP-AR-GKE

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-cd-ar-gke.yaml'
  workflow_dispatch:

env:
  PROJECT_ID: qwiklabs-gcp-03-7e692432f164
  REGION: us-centra1
  REPOSITORY: demo-ar
  IMAGE1_NAME: application-service
  IMAGE2_NAME: patient-service
  # HELM_RELEASE: patient-release
  # HELM_CHART_PATH: ./helm/patient 
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1
  GKE_NAMESPACE: default
  DEPLOYMENT_NAME: application-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Authenticate to GCP using Service Account Key
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3️⃣ Setup gcloud
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    # 4️⃣ Configure Docker for Artifact Registry
    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    # Step 4: Set image tag (same as before)
    - name: Set image tags
      id: vars
      run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

# Step 5: Build and push Docker image to Artifact Registry
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./application-service
        file: ./application-service/Dockerfile
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE1_NAME }}:latest
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE1_NAME }}:${{ steps.vars.outputs.TAG }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    # 8️⃣ Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl create deployment ${{ env.DEPLOYMENT_NAME }} \
          --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE1_NAME }}:${{ github.sha }} \
          -n ${{ env.GKE_NAMESPACE }}

